### ISSUE TITLE
Can't run example training

### ISSUE THREAD

**Issue by francoishernandez** [episodeyang/deep-auto-punctuation#1]
Hi there,

As a first contact with your project I am trying to run it 'as is', but it seems I can't run a proper training with the example notebook.

All preliminary steps work fine, but when launching the training step, the only output I get is `0it [00:00, ?it/s]`, repeatedly, and nothing further is happening either on logs or in the directories (nothing is saved).

By the way, I believe some indentation is missed for the last 2 lines of the block (need to be inside the for loop for `batch_ind` to be defined).

I managed to test the pretrained models though.

Thanks for your implementation anyways, and thanks in advance for your reply!
Hope to get the code running properly soon :)

F

**Comment by geyang** [comment]
let me take a quick look!

**Comment by francoishernandez** [comment]
Hi again,

Did you have a chance to take a look?

Thanks :)
F

**Comment by geyang** [comment]
Hey @francoishernandez I just took a look! Looks like you need to run the `visdom.sever` first. 

The python version I use is 3.6.0 for this project.

https://github.com/episodeyang/deep-auto-punctuation/commit/747595870a3d092487952e53d75bbfbc7ab46592

The code is actually correct, I want to save the check point not at every batch but at the end of each epoch

**Comment by francoishernandez** [comment]
Seems like it's working now, thanks! :)

![capture d ecran 2017-07-31 a 22 15 44](https://user-images.githubusercontent.com/14880403/28796451-dc3d55b2-763d-11e7-9ec8-4976fd0c6579.png)

**Comment by geyang** [comment]
great!
