### ISSUE TITLE
view size not compatible with input tensor size and stride

### ISSUE THREAD

**Issue by sebastianvermaas** [episodeyang/deep-auto-punctuation#3]
`Traceback (most recent call last):
  File "train.py", line 71, in <module>
    egdt.forward(input_, target_)
  File "/home/flow/deep-auto-punctuation/model.py", line 90, in forward
    self.next_(input_batch)
  File "/home/flow/deep-auto-punctuation/model.py", line 111, in next_
    self.output, self.hidden = self.model(self.embed(input_text), self.hidden)
  File "/home/flow/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/flow/deep-auto-punctuation/model.py", line 32, in forward
    output = self.decoder(gru_output.view(-1, self.hidden_size * self.bi_mul))
RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/TH/generic/THTensor.cpp:237
`

Any idea what could be causing this?

**Comment by adrifloresm** [comment]
I am running into the same issue. Did you resolve it?

**Comment by gisforgirard** [comment]
check my pull request :)

**Comment by geyang** [comment]
Thanks @gisforgirard , merged.
@pineappleflow  check out the master with @gisforgirard 's commit -- does that PR fix the issue?
